"""Custom fields för transportbokning. Skapas vid installation och migrate (install.after_install)."""

EGNA = "eval:doc.fraktsatt=='Egna mått'"
FORP = "eval:doc.fraktsatt=='Förpackning'"


def get_custom_fields():
	return {
		"Item": [
			{
				"fieldname": "frakt_section",
				"label": "Frakt",
				"fieldtype": "Section Break",
				"insert_after": "weight_uom",
			},
			{
				"fieldname": "fraktsatt",
				"label": "Fraktsätt",
				"fieldtype": "Select",
				"options": "\nEgna mått\nFörpackning",
				"insert_after": "frakt_section",
				"description": "Egna mått: artikeln är sitt eget kolli. Förpackning: artikeln packas i en förpackningstyp.",
			},
			{
				"fieldname": "frakt_kollityp",
				"label": "Kollityp",
				"fieldtype": "Select",
				"options": "Paket\nPall",
				"default": "Paket",
				"depends_on": EGNA,
				"insert_after": "fraktsatt",
			},
			{
				"fieldname": "frakt_langd_cm",
				"label": "Längd (cm)",
				"fieldtype": "Float",
				"depends_on": EGNA,
				"insert_after": "frakt_kollityp",
			},
			{
				"fieldname": "frakt_bredd_cm",
				"label": "Bredd (cm)",
				"fieldtype": "Float",
				"depends_on": EGNA,
				"insert_after": "frakt_langd_cm",
			},
			{
				"fieldname": "frakt_hojd_cm",
				"label": "Höjd (cm)",
				"fieldtype": "Float",
				"depends_on": EGNA,
				"insert_after": "frakt_bredd_cm",
			},
			{"fieldname": "frakt_column", "fieldtype": "Column Break", "insert_after": "frakt_hojd_cm"},
			{
				"fieldname": "frakt_stapelbar",
				"label": "Stapelbar",
				"fieldtype": "Check",
				"default": "1",
				"depends_on": EGNA,
				"insert_after": "frakt_column",
			},
			{
				"fieldname": "frakt_flakmeter",
				"label": "Flakmeter",
				"fieldtype": "Float",
				"depends_on": EGNA,
				"insert_after": "frakt_stapelbar",
			},
			{
				"fieldname": "frakt_pallplatser",
				"label": "Pallplatser",
				"fieldtype": "Float",
				"depends_on": EGNA,
				"insert_after": "frakt_flakmeter",
				"description": "Fyller i flakmeter (0,4 per pallplats) om flakmeter är tomt",
			},
			{
				"fieldname": "forpackningstyp",
				"label": "Förpackningstyp",
				"fieldtype": "Link",
				"options": "Forpackningstyp",
				"depends_on": FORP,
				"insert_after": "frakt_pallplatser",
			},
			{
				"fieldname": "antal_per_forpackning",
				"label": "Antal per förpackning",
				"fieldtype": "Float",
				"depends_on": FORP,
				"insert_after": "forpackningstyp",
				"description": "I lagerenhet",
			},
		],
		"Sales Invoice Item": [
			{
				"fieldname": "frakt_shipment",
				"label": "Försändelse (frakt)",
				"fieldtype": "Link",
				"options": "Shipment",
				"read_only": 1,
				"no_copy": 1,
				"insert_after": "item_name",
			},
		],
		"Customer": [
			{
				"fieldname": "forvald_fraktprodukt",
				"label": "Förvald fraktprodukt",
				"fieldtype": "Link",
				"options": "Fraktprodukt",
				"insert_after": "default_price_list",
			},
		],
		"Quotation": [
			{
				"fieldname": "fraktprodukt",
				"label": "Fraktprodukt",
				"fieldtype": "Link",
				"options": "Fraktprodukt",
				"read_only": 1,
				"insert_after": "taxes_and_charges",
			},
		],
		"Sales Order": [
			{
				"fieldname": "fraktprodukt",
				"label": "Fraktprodukt",
				"fieldtype": "Link",
				"options": "Fraktprodukt",
				"read_only": 1,
				"insert_after": "taxes_and_charges",
			},
		],
		"Shipment": [
			{
				"fieldname": "frakt_section",
				"label": "Fraktbokning",
				"fieldtype": "Section Break",
				"insert_after": "tracking_status_info",
			},
			{
				"fieldname": "avsandarens_referens",
				"label": "Avsändarens referens",
				"fieldtype": "Data",
				"insert_after": "frakt_section",
			},
			{
				"fieldname": "mottagarens_referens",
				"label": "Mottagarens referens",
				"fieldtype": "Data",
				"insert_after": "avsandarens_referens",
			},
			{
				"fieldname": "fraktprodukt",
				"label": "Fraktprodukt",
				"fieldtype": "Link",
				"options": "Fraktprodukt",
				"insert_after": "mottagarens_referens",
			},
			{"fieldname": "frakt_column_1", "fieldtype": "Column Break", "insert_after": "fraktprodukt"},
			{
				"fieldname": "fraktpris",
				"label": "Fraktpris",
				"fieldtype": "Currency",
				"options": "fraktpris_valuta",
				"read_only": 1,
				"insert_after": "frakt_column_1",
			},
			{
				"fieldname": "fraktpris_valuta",
				"label": "Valuta",
				"fieldtype": "Link",
				"options": "Currency",
				"read_only": 1,
				"insert_after": "fraktpris",
			},
			{
				"fieldname": "kundpris",
				"label": "Fraktpris till kund",
				"fieldtype": "Currency",
				"allow_on_submit": 1,
				"insert_after": "fraktpris_valuta",
			},
			{
				"fieldname": "pris_hamtat",
				"label": "Pris hämtat",
				"fieldtype": "Datetime",
				"read_only": 1,
				"insert_after": "kundpris",
			},
			{"fieldname": "frakt_column_2", "fieldtype": "Column Break", "insert_after": "pris_hamtat"},
			{
				"fieldname": "sendify_id",
				"label": "Sendify-id",
				"fieldtype": "Data",
				"read_only": 1,
				"no_copy": 1,
				"insert_after": "frakt_column_2",
			},
			{
				"fieldname": "dokumenttyper",
				"label": "Dokumenttyper",
				"fieldtype": "Data",
				"read_only": 1,
				"hidden": 1,
				"no_copy": 1,
				"insert_after": "sendify_id",
			},
			{
				"fieldname": "etikett_hamtad",
				"label": "Fraktsedel hämtad",
				"fieldtype": "Check",
				"read_only": 1,
				"no_copy": 1,
				"insert_after": "dokumenttyper",
			},
			{
				"fieldname": "senaste_sparning",
				"label": "Senaste spårning",
				"fieldtype": "Data",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"insert_after": "etikett_hamtad",
			},
			{
				"fieldname": "senaste_sparningsstatus",
				"label": "Spårningsstatus hos transportören",
				"fieldtype": "Data",
				"read_only": 1,
				"hidden": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"insert_after": "senaste_sparning",
			},
			{
				"fieldname": "sparning_section",
				"label": "Spårningshändelser",
				"fieldtype": "Section Break",
				"collapsible": 1,
				"insert_after": "senaste_sparningsstatus",
			},
			{
				"fieldname": "sparningshandelser",
				"label": "Spårningshändelser",
				"fieldtype": "Table",
				"options": "Sparningshandelse",
				"read_only": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
				"insert_after": "sparning_section",
			},
		],
		"Shipment Parcel": [
			{
				"fieldname": "kollityp",
				"label": "Kollityp",
				"fieldtype": "Select",
				"options": "Paket\nPall\nÖvrigt",
				"default": "Paket",
				"in_list_view": 1,
				"insert_after": "count",
			},
			{
				"fieldname": "stapelbar",
				"label": "Stapelbar",
				"fieldtype": "Check",
				"default": "1",
				"insert_after": "kollityp",
			},
			{
				"fieldname": "flakmeter",
				"label": "Flakmeter",
				"fieldtype": "Float",
				"insert_after": "stapelbar",
			},
			{
				"fieldname": "beskrivning",
				"label": "Beskrivning",
				"fieldtype": "Data",
				"insert_after": "flakmeter",
			},
		],
	}
